define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for OnboardingModal generated by Appery.io
         * @module OnboardingModal
         */
        APP.controller('OnboardingModalController', ['$scope', 'Apperyio', OnboardingModalController]);

        function OnboardingModalController($scope, Apperyio) {
            // user controller variables
            $scope.page = Apperyio.EntityAPI('String');
            // user controller functions
            /**
             * @function closeModal
             */
            $scope.closeModal = function() {
                $scope.modal.hide();
            };
            /**
             * @function init
             */
            $scope.init = function() {
                $scope.page = "one";
            };
            /**
             * @function nextPage
             */
            $scope.nextPage = function() {
                if ($scope.page == "one") {
                    $scope.page = "two";
                } else if ($scope.page == "two") {
                    $scope.page = "three";
                } else if ($scope.page == "three") {
                    $scope.page = "four";
                }
            };
            /**
             * @function previousPage
             */
            $scope.previousPage = function() {
                if ($scope.page == "two") {
                    $scope.page = "one";
                } else if ($scope.page == "three") {
                    $scope.page = "two";
                } else if ($scope.page == "four") {
                    $scope.page = "three";
                }
            };
            /**
             * @function pageOne
             */
            $scope.pageOne = function() {
                $scope.page = "one";
            };
            /**
             * @function pageTwo
             */
            $scope.pageTwo = function() {
                $scope.page = "two";
            };
            /**
             * @function pageThree
             */
            $scope.pageThree = function() {
                $scope.page = "three";
            };
            /**
             * @function pageFour
             */
            $scope.pageFour = function() {
                $scope.page = "four";
            };
        }
    });