define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for DashboardOrganization generated by Appery.io
         * @module DashboardOrganization
         */
        APP.controller('DashboardOrganization', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.organizationData = Apperyio.EntityAPI('OrganizationData');
            $scope.report = Apperyio.EntityAPI('Number');
            $scope.show = Apperyio.EntityAPI('Number');
            $scope.attendanceDetails = Apperyio.EntityAPI('AttendanceDetails');
            $scope.ticketsByZip = Apperyio.EntityAPI('TicketsByZip');
            $scope.org = Apperyio.EntityAPI('Number');
            $scope.showSpinner1 = Apperyio.EntityAPI('Boolean');
            $scope.peerData = Apperyio.EntityAPI('PeerData');
            $scope.showSpinner2 = Apperyio.EntityAPI('Boolean');
            $scope.orgData = Apperyio.EntityAPI('OrganizationData');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                //window.location.reload(true);
                $scope.showSpinner1 = false;
                $scope.pieoptions = {
                    chart: {
                        type: 'pieChart',
                        height: 680,
                        x: function(d) {
                            return d.key;
                        },
                        y: function(d) {
                            return d.y;
                        },
                        showLabels: false,
                        duration: 500,
                        labelThreshold: 0.01,
                        labelSunbeamLayout: true,
                        margin: {
                            top: 15,
                            right: 15,
                            bottom: 15,
                            left: 15
                        },
                        showLegend: false,
                        noData: 'Click Run to View Chart'
                    }
                };
                $scope.piedata = [];
                $scope.bulletoptions = {
                    chart: {
                        type: 'bulletChart',
                        duration: 500,
                        height: 75,
                        tooltip: {
                            enabled: false
                        },
                        margin: {
                            top: 25,
                            right: 15,
                            bottom: 25,
                            left: 15,
                        },
                        noData: 'Click Run Show to View Chart'
                    }
                };
                $scope.bulletdata = {};
                $scope.discretebaroptions = {
                    chart: {
                        type: 'discreteBarChart',
                        height: 210,
                        margin: {
                            top: 20,
                            right: 20,
                            bottom: 50,
                            left: 55
                        },
                        x: function(d) {
                            return d.label;
                        },
                        y: function(d) {
                            return d.value;
                        },
                        showValues: true,
                        valueFormat: function(d) {
                            return d3.format(',.2f')(d);
                        },
                        duration: 500,
                        xAxis: {
                            //axisLabel: 'X Axis'
                        },
                        yAxis: {
                            axisLabel: 'Average Price',
                            axisLabelDistance: -10
                        },
                        noData: 'Click Run Show to View Chart'
                    }
                };
                $scope.discretebardata = [];
                $scope.discretebareventoptions = {
                    chart: {
                        type: 'discreteBarChart',
                        height: 210,
                        margin: {
                            top: 20,
                            right: 20,
                            bottom: 50,
                            left: 55
                        },
                        x: function(d) {
                            return d.label;
                        },
                        y: function(d) {
                            return d.value;
                        },
                        showValues: true,
                        valueFormat: function(d) {
                            return d3.format(',.0f')(d);
                        },
                        duration: 500,
                        xAxis: {
                            //axisLabel: 'X Axis'
                        },
                        yAxis: {
                            axisLabel: 'Average Price',
                            axisLabelDistance: -10
                        },
                        noData: 'Click Run Show to View Chart'
                    }
                };
                $scope.discretebareventdata = [];
                $scope.discretebareventrevoptions = {
                    chart: {
                        type: 'discreteBarChart',
                        height: 210,
                        margin: {
                            top: 20,
                            right: 20,
                            bottom: 50,
                            left: 55
                        },
                        x: function(d) {
                            return d.label;
                        },
                        y: function(d) {
                            return d.value;
                        },
                        showValues: true,
                        valueFormat: function(d) {
                            return d3.format(',.0f')(d);
                        },
                        duration: 500,
                        xAxis: {
                            //axisLabel: 'X Axis'
                        },
                        yAxis: {
                            axisLabel: 'Average Revenue',
                            axisLabelDistance: -10
                        },
                        noData: 'Click Run Show to View Chart'
                    }
                };
                $scope.discretebareventrevdata = [];
                $scope.historicaldiscretebaroptions = {
                    chart: {
                        type: 'discreteBarChart',
                        height: 525,
                        margin: {
                            top: 20,
                            right: 20,
                            bottom: 50,
                            left: 55
                        },
                        x: function(d) {
                            return d.label;
                        },
                        y: function(d) {
                            return d.value;
                        },
                        showValues: true,
                        valueFormat: function(d) {
                            return d3.format(',.0f')(d);
                        },
                        duration: 500,
                        xAxis: {
                            //axisLabel: 'X Axis'
                        },
                        yAxis: {
                            axisLabel: 'Total Attendance',
                            axisLabelDistance: -10
                        },
                        staggerLabels: true,
                        noData: 'Click Run Show to View Chart'
                    }
                };
                $scope.historicaldiscretebardata = [];
                $scope.show = null;
                $scope.org = null;
                $scope.organizationData = [];
                $scope.bulletdata = {};
                $scope.capacitydata = {};
                $scope.attendanceDetails = [];
                $scope.ticketsByZip = [];
                $scope.peerData = [];
                $scope.button = "organization";
                var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                    animation: 'slide-in-up', // The animation to show & hide with
                    focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                    backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                };
                if ($scope.windowWidth > 1499) {
                    Apperyio.get('Modals').loadModal("OnboardingModal").then( /*|service_bookmark|bookmark|C9E48A54-5093-F922-6378-4820545D8E54||8671|*/
                        function(modalInstance) {
                            modalInstance.open(modalOptions).then(function(modal) {
                                modal.scope.modal = modal;
                                modal.scope.windowWidth = $scope.windowWidth;
                                modal.show();
                            });
                        },
                        function(error) {
                            console.log(error);
                        });
                } else {
                    Apperyio.get('Modals').loadModal("OnboardingModalSmall").then(
                        function(modalInstance) {
                            modalInstance.open(modalOptions).then(function(modal) {
                                modal.scope.modal = modal;
                                modal.scope.windowWidth = $scope.windowWidth;
                                modal.show();
                            });
                        },
                        function(error) {
                            console.log(error);
                        });
                }
            };
            /**
             * @function choosePieDisplay
             * @param rept
             */
            $scope.choosePieDisplay = function(rept) {
                $scope.piedata = [];
                $scope.organizationData = [];
                rept = $scope.report;
                $scope.button = "report";
            };
            /**
             * @function chooseOrganization
             * @param org
             */
            $scope.chooseOrganization = function(org) {
                $scope.piedata = [];
                $scope.organizationData = [];
                $scope.bulletdata = {};
                $scope.capacitydata = {};
                $scope.horizontalbardata = [];
                $scope.discretebardata = [];
                $scope.discretebareventdata = [];
                $scope.discretebareventrevdata = [];
                $scope.show = null;
                $scope.org = org;
                $scope.button = "organization";
                //$scope.$apply();
            };
            /**
             * @function getDataZero
             * @param orgn
             */
            $scope.getDataZero = function(orgn) {
                $scope.showSpinner1 = true;
                var organiz = $scope.organizations[orgn].id;
                $scope.userValid = '';
                $scope.getPrivateIP();
                $scope.getActiveKey();
                var requestData = {};
                requestData = (function mapping8018($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var activeKey_scope = $scope.activeKey;
                    requestData.params.activeKey = activeKey_scope;
                    return requestData;
                    /*|button_mapping|onbeforesend|0A579B7C-29EB-F2F1-5707-123CB5D10538||1017|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("TPretrieveUserInformation")(requestData).then( /*|service_bookmark|bookmark|0A579B7C-29EB-F2F1-5707-123CB5D10538||4495|*/
                    function(success) { // success callback
                        (function mapping8554(success, $scope) {
                            var sessionData_scope = $scope.sessionData;
                            _.set(sessionData_scope, 'id', success.data.id);
                            _.set(sessionData_scope, 'userID', success.data.userID);
                            _.set(sessionData_scope, 'activeKey', success.data.activeKey);
                            _.set(sessionData_scope, 'ipAddress', success.data.ipAddress);
                            _.set(sessionData_scope, 'expirationDate', success.data.expirationDate);
                            _.set(sessionData_scope, 'status', success.data.status);
                            _.set(sessionData_scope, 'user', success.data.user);
                            _.set(sessionData_scope, 'user.id', success.data.user.id);
                            _.set(sessionData_scope, 'user.username', success.data.user.username);
                            _.set(sessionData_scope, 'user.email', success.data.user.email);
                            $scope.sessionData = sessionData_scope;
                            /*|button_mapping|onsuccess|0A579B7C-29EB-F2F1-5707-123CB5D10538||7278|*/
                            if ($scope.activeKey == $scope.sessionData.activeKey) {
                                var requestData = {};
                                requestData = (function mapping3074($scope) {
                                    var requestData = {};
                                    requestData.data = {};
                                    var otherkeys_scope = $scope.otherkeys;
                                    _.set(requestData.data, 'admin', otherkeys_scope.otheradmin);
                                    _.set(requestData.data, 'password', otherkeys_scope.otherpassword);
                                    _.set(requestData.data, 'host', otherkeys_scope.otherhost);
                                    var sessionData_scope = $scope.sessionData;
                                    _.set(requestData.data, 'userID', sessionData_scope.userID);
                                    _.set(requestData.data, 'activeKey', sessionData_scope.activeKey);
                                    var privateIP_scope = $scope.privateIP;
                                    _.set(requestData.data, 'ipAddress', privateIP_scope);
                                    return requestData;
                                    /*|button_mapping|onbeforesend|6B3F5F17-D8D2-5ED5-55A5-2A3308650B34||3074|*/
                                })($scope);
                                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                                Apperyio.get("rstudioTPuserValidCheck")(requestData).then( /*|service_bookmark|bookmark|6B3F5F17-D8D2-5ED5-55A5-2A3308650B34||9373|*/
                                    function(success) { // success callback
                                        (function mapping3739(success, $scope) {
                                            var userValid_scope = $scope.userValid;
                                            userValid_scope = success.data[0];
                                            $scope.userValid = userValid_scope;
                                            /*|button_mapping|onsuccess|6B3F5F17-D8D2-5ED5-55A5-2A3308650B34||3739|*/
                                            if ($scope.userValid == 'TRUE') {
                                                var requestData = {};
                                                requestData = (function mapping5140($scope) {
                                                    var requestData = {};
                                                    requestData.data = {};
                                                    var keys_scope = $scope.keys;
                                                    _.set(requestData.data, 'admin', keys_scope.admin);
                                                    _.set(requestData.data, 'password', keys_scope.password);
                                                    _.set(requestData.data, 'host', keys_scope.host);
                                                    _.set(requestData.data, 'dbname', keys_scope.dbname);
                                                    _.set(requestData.data, 'tickettable', keys_scope.tickettable);
                                                    _.set(requestData.data, 'venuetable', keys_scope.venuetable);
                                                    _.set(requestData.data, 'eventtable', keys_scope.eventtable);
                                                    _.set(requestData.data, 'productiontable', keys_scope.productiontable);
                                                    var dateRange_scope = $scope.dateRange;
                                                    _.set(requestData.data, 'startDate', dateRange_scope.startDate);
                                                    _.set(requestData.data, 'endDate', dateRange_scope.endDate);
                                                    var org_scope = organiz;
                                                    _.set(requestData.data, 'organizationID', org_scope);
                                                    return requestData;
                                                    /*CLICK TO EDIT MAPPING*/
                                                })($scope);
                                                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                                                Apperyio.get("rstudioTPcompanyShowsPerformance")(requestData).then(
                                                    function(success) { // success callback
                                                        (function mapping1799(success, $scope) {
                                                            var organizationData_scope = $scope.orgData;
                                                            for (var i = 0, l = success.data.length; i < l; i++) {
                                                                _.set(organizationData_scope, '[' + i + '].ShowID', success.data[i]['tttcProductionID.id']);
                                                                _.set(organizationData_scope, '[' + i + '].ShowTitles', success.data[i]['tttcProductionID.title']);
                                                                _.set(organizationData_scope, '[' + i + '].NetSales', success.data[i].netSales);
                                                                _.set(organizationData_scope, '[' + i + '].NetQty', success.data[i].netAttendedTickets);
                                                                _.set(organizationData_scope, '[' + i + '].Purchased', success.data[i].netPurchasedTickets);
                                                                _.set(organizationData_scope, '[' + i + '].Comp', success.data[i].totalCompedProdTkts);
                                                                _.set(organizationData_scope, '[' + i + '].Refunded', success.data[i].totalRefundedProdTkts);
                                                                _.set(organizationData_scope, '[' + i + '].PctCapacity', success.data[i].pctCapacity);
                                                                _.set(organizationData_scope, '[' + i + '].numEvents', success.data[i].numEvents);
                                                                _.set(organizationData_scope, '[' + i + '].PctTotalPurchased', success.data[i].pctTotalPurchasedTkts);
                                                                _.set(organizationData_scope, '[' + i + '].PctPaid', success.data[i].pctPaidAttendees);
                                                                _.set(organizationData_scope, '[' + i + '].AvgTktPrice', success.data[i].avgTktPrice);
                                                                _.set(organizationData_scope, '[' + i + '].Index', success.data[i].index);
                                                            }
                                                            $scope.orgData = organizationData_scope;
                                                            /*CLICK TO EDIT MAPPING*/
                                                            $scope.organizationData = $scope.orgData.splice(0, $scope.orgData.length - 1);
                                                            $scope.showSpinner1 = false;
                                                            var piedata_scope = $scope.piedata;
                                                            piedata_scope = $scope.organizationData;
                                                            for (var j = 0; j < $scope.organizationData.length; j++) {
                                                                piedata_scope[j].key = $scope.organizationData[j].ShowTitles;
                                                                piedata_scope[j].y = $scope.organizationData[j].PctTotalPurchased;
                                                            }
                                                            $scope.piedata = piedata_scope;
                                                        })(success, $scope);
                                                    },
                                                    function(error) { // callback to handle request error
                                                        var $ionicPopup = Apperyio.get("$ionicPopup");
                                                        var alertPopup = $ionicPopup.alert({
                                                            title: 'This Company Has No Data',
                                                            template: "There is no ticketing data available for this company. If you believe this message was received in error, please contact us at support@theatreprofile.com and let us know."
                                                        });
                                                        $scope.showSpinner1 = false;
                                                    },
                                                    function(notify) { // notify callback, can fire few times
                                                    });
                                            } else {
                                                var $ionicPopup = Apperyio.get("$ionicPopup");
                                                var alertPopup = $ionicPopup.alert({
                                                    title: 'Session No Longer Active',
                                                    template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                                                });
                                            }
                                        })(success, $scope);
                                    },
                                    function(error) { // callback to handle request error
                                    },
                                    function(notify) { // notify callback, can fire few times
                                    });
                            } else {
                                var $ionicPopup = Apperyio.get("$ionicPopup");
                                var alertPopup = $ionicPopup.alert({
                                    title: 'Session No Longer Active',
                                    template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                                });
                            }
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        var $ionicPopup = Apperyio.get("$ionicPopup");
                        var alertPopup = $ionicPopup.alert({
                            title: 'Session No Longer Active',
                            template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                        });
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function chooseShow
             * @param shw
             * @param org
             */
            $scope.chooseShow = function(shw, org) {
                //shw = $scope.show;
                $scope.showSpinner2 = true;
                $scope.userValid = '';
                $scope.getPrivateIP();
                $scope.getActiveKey();
                $scope.show = shw;
                var requestData = {};
                requestData = (function mapping4111($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var activeKey_scope = $scope.activeKey;
                    requestData.params.activeKey = activeKey_scope;
                    return requestData;
                    /*|button_mapping|onbeforesend|0207EE31-FB17-A717-8EB9-8C080EE915CD||4111|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("TPretrieveUserInformation")(requestData).then( /*|service_bookmark|bookmark|0207EE31-FB17-A717-8EB9-8C080EE915CD||3213|*/
                    function(success) { // success callback
                        (function mapping9923(success, $scope) {
                            var sessionData_scope = $scope.sessionData;
                            _.set(sessionData_scope, 'id', success.data.id);
                            _.set(sessionData_scope, 'userID', success.data.userID);
                            _.set(sessionData_scope, 'activeKey', success.data.activeKey);
                            _.set(sessionData_scope, 'ipAddress', success.data.ipAddress);
                            _.set(sessionData_scope, 'expirationDate', success.data.expirationDate);
                            _.set(sessionData_scope, 'status', success.data.status);
                            _.set(sessionData_scope, 'user', success.data.user);
                            _.set(sessionData_scope, 'user.id', success.data.user.id);
                            _.set(sessionData_scope, 'user.username', success.data.user.username);
                            _.set(sessionData_scope, 'user.email', success.data.user.email);
                            $scope.sessionData = sessionData_scope;
                            /*|button_mapping|onsuccess|0207EE31-FB17-A717-8EB9-8C080EE915CD||9923|*/
                            if ($scope.activeKey == $scope.sessionData.activeKey) {
                                var requestData = {};
                                requestData = (function mapping3130($scope) {
                                    var requestData = {};
                                    requestData.data = {};
                                    var otherkeys_scope = $scope.otherkeys;
                                    _.set(requestData.data, 'admin', otherkeys_scope.otheradmin);
                                    _.set(requestData.data, 'password', otherkeys_scope.otherpassword);
                                    _.set(requestData.data, 'host', otherkeys_scope.otherhost);
                                    var sessionData_scope = $scope.sessionData;
                                    _.set(requestData.data, 'userID', sessionData_scope.userID);
                                    _.set(requestData.data, 'activeKey', sessionData_scope.activeKey);
                                    var privateIP_scope = $scope.privateIP;
                                    _.set(requestData.data, 'ipAddress', privateIP_scope);
                                    return requestData;
                                    /*|button_mapping|onbeforesend|17D4E4AC-87BA-73FC-9710-B492A2CC04BE||3130|*/
                                })($scope);
                                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                                Apperyio.get("rstudioTPuserValidCheck")(requestData).then( /*|service_bookmark|bookmark|17D4E4AC-87BA-73FC-9710-B492A2CC04BE||3230|*/
                                    function(success) { // success callback
                                        (function mapping5489(success, $scope) {
                                            var userValid_scope = $scope.userValid;
                                            userValid_scope = success.data[0];
                                            $scope.userValid = userValid_scope;
                                            /*|button_mapping|onsuccess|17D4E4AC-87BA-73FC-9710-B492A2CC04BE||5489|*/
                                            if ($scope.userValid == 'TRUE') {
                                                $scope.getAttendanceDetails(shw);
                                            } else {
                                                var $ionicPopup = Apperyio.get("$ionicPopup");
                                                var alertPopup = $ionicPopup.alert({
                                                    title: 'Session No Longer Active',
                                                    template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                                                });
                                            }
                                        })(success, $scope);
                                    },
                                    function(error) { // callback to handle request error
                                    },
                                    function(notify) { // notify callback, can fire few times
                                    });
                            } else {
                                var $ionicPopup = Apperyio.get("$ionicPopup");
                                var alertPopup = $ionicPopup.alert({
                                    title: 'Session No Longer Active',
                                    template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                                });
                            }
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        var $ionicPopup = Apperyio.get("$ionicPopup");
                        var alertPopup = $ionicPopup.alert({
                            title: 'Session No Longer Active',
                            template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                        });
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function getAttendanceDetails
             * @param shw
             */
            $scope.getAttendanceDetails = function(shw) {
                var requestData = {};
                requestData = (function mapping2050($scope) {
                    var requestData = {};
                    requestData.data = {};
                    var show_scope = $scope.organizationData[shw].ShowID;
                    _.set(requestData.data, 'productionID', show_scope);
                    var keys_scope = $scope.keys;
                    _.set(requestData.data, 'admin', keys_scope.admin);
                    _.set(requestData.data, 'password', keys_scope.password);
                    _.set(requestData.data, 'host', keys_scope.host);
                    _.set(requestData.data, 'tickettable', keys_scope.tickettable);
                    _.set(requestData.data, 'eventtable', keys_scope.eventtable);
                    _.set(requestData.data, 'dbname', keys_scope.dbname);
                    var dateRange_scope = $scope.dateRange;
                    _.set(requestData.data, 'startDate', dateRange_scope.startDate);
                    _.set(requestData.data, 'endDate', dateRange_scope.endDate);
                    return requestData;
                    /*CLICK TO EDIT MAPPING*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("rstudioTPshowEventDetails")(requestData).then(
                    function(success) { // success callback
                        (function mapping6643(success, $scope) {
                            var attendanceDetails_scope = $scope.attendanceDetails;
                            for (var i = 0, l = success.data.length; i < l; i++) {
                                for (var i1 = 0, l1 = success.data[i].length; i1 < l1; i1++) {
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].showTimes', success.data[i][i1].eventDate);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].attendance', success.data[i][i1].numAttended);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].wkdayNum', success.data[i][i1].wdayNum);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].dayName', success.data[i][i1].weekday);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].days', success.data[i][i1]['days.i.']);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].attendanceAvg', success.data[i][i1].avgAttendance);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].times', success.data[i][i1]['times.i.']);
                                    _.set(attendanceDetails_scope, '[' + i + '][' + i1 + '].time', success.data[i][i1].time);
                                }
                            }
                            $scope.attendanceDetails = attendanceDetails_scope;
                            /*CLICK TO EDIT MAPPING*/
                            var historicalvalues_scope = $scope.historicalvalues;
                            historicalvalues_scope = $scope.attendanceDetails[0];
                            for (var j = 0; j < $scope.attendanceDetails[0].length; j++) {
                                historicalvalues_scope[j].label = $scope.attendanceDetails[0][j].showTimes;
                                historicalvalues_scope[j].value = $scope.attendanceDetails[0][j].attendance;
                                historicalvalues_scope[j].color = "#444444";
                            }
                            $scope.historicalvalues = historicalvalues_scope;
                            $scope.historicaldiscretebardata = [{
                                key: "Our Attendance",
                                values: $scope.historicalvalues
                            }];
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                requestData = (function mapping6235($scope) {
                    var requestData = {};
                    requestData.data = {};
                    var show_scope = $scope.organizationData[shw].ShowID;
                    _.set(requestData.data, 'productionID', show_scope);
                    var keys_scope = $scope.keys;
                    _.set(requestData.data, 'admin', keys_scope.admin);
                    _.set(requestData.data, 'password', keys_scope.password);
                    _.set(requestData.data, 'host', keys_scope.host);
                    _.set(requestData.data, 'tickettable', keys_scope.tickettable);
                    _.set(requestData.data, 'usertable', keys_scope.usertable);
                    _.set(requestData.data, 'eventtable', keys_scope.eventtable);
                    _.set(requestData.data, 'dbname', keys_scope.dbname);
                    _.set(requestData.data, 'geotable', keys_scope.geotable);
                    _.set(requestData.data, 'tatheatredb', keys_scope.tatheatredb);
                    var otherkeys_scope = $scope.otherkeys;
                    _.set(requestData.data, 'otheradmin', otherkeys_scope.otheradmin);
                    _.set(requestData.data, 'otherpassword', otherkeys_scope.otherpassword);
                    _.set(requestData.data, 'otherhost', otherkeys_scope.otherhost);
                    var dateRange_scope = $scope.$parent.$parent.dateRange;
                    _.set(requestData.data, 'startDate', dateRange_scope.startDate);
                    _.set(requestData.data, 'endDate', dateRange_scope.endDate);
                    return requestData;
                    /*CLICK TO EDIT MAPPING*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("rstudioTPshowEventGeography")(requestData).then(
                    function(success) { // success callback
                        (function mapping9091(success, $scope) {
                            var ticketsByZip_scope = $scope.ticketsByZip;
                            for (var i = 0, l = success.data.length; i < l; i++) {
                                _.set(ticketsByZip_scope, '[' + i + '].uniqueZipCodes', success.data[i].zipCodesEvents);
                                _.set(ticketsByZip_scope, '[' + i + '].numAttended', success.data[i].attendance);
                                _.set(ticketsByZip_scope, '[' + i + '].city', success.data[i].city);
                                //_.set(ticketsByZip_scope, '[' + i + '].index', success.data[i].index);
                            }
                            $scope.ticketsByZip = ticketsByZip_scope;
                            /*CLICK TO EDIT MAPPING*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                $scope.peerService(shw);
            };
            /**
             * @function peerService
             * @param shw
             */
            $scope.peerService = function(shw) {
                var requestData = {};
                requestData = (function mapping6378($scope) {
                    var requestData = {};
                    requestData.data = {};
                    var show_scope = $scope.organizationData[shw].ShowID;
                    _.set(requestData.data, 'productionID', show_scope);
                    var keys_scope = $scope.keys;
                    _.set(requestData.data, 'admin', keys_scope.admin);
                    _.set(requestData.data, 'password', keys_scope.password);
                    _.set(requestData.data, 'host', keys_scope.host);
                    _.set(requestData.data, 'tickettable', keys_scope.tickettable);
                    _.set(requestData.data, 'venuetable', keys_scope.venuetable);
                    _.set(requestData.data, 'eventtable', keys_scope.eventtable);
                    _.set(requestData.data, 'dbname', keys_scope.dbname);
                    _.set(requestData.data, 'productiontable', keys_scope.productiontable);
                    _.set(requestData.data, 'showtable', keys_scope.showtable);
                    _.set(requestData.data, 'tpshowtable', keys_scope.tpshowtable);
                    return requestData;
                    /*CLICK TO EDIT MAPPING*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("rstudioTPshowPeerComparison")(requestData).then(
                    function(success) { // success callback
                        (function mapping9347(success, $scope) {
                            var peerData_scope = $scope.peerData;
                            for (var i = 0, l = success.data.length; i < l; i++) {
                                _.set(peerData_scope, '[' + i + '].tpShowID', success.data[i]['tpShowID.tpShowID']);
                                _.set(peerData_scope, '[' + i + '].tpShowTitle', success.data[i]['tpShowID.title']);
                                _.set(peerData_scope, '[' + i + '].netSales', success.data[i].netSales);
                                _.set(peerData_scope, '[' + i + '].netAttendedTickets', success.data[i].netAttendedTickets);
                                _.set(peerData_scope, '[' + i + '].netPurchasedTickets', success.data[i].netPurchasedTickets);
                                _.set(peerData_scope, '[' + i + '].totalCompedProdTkts', success.data[i].totalCompedProdTkts);
                                _.set(peerData_scope, '[' + i + '].totalRefundedProdTkts', success.data[i].totalRefundedProdTkts);
                                _.set(peerData_scope, '[' + i + '].pctCapacity', success.data[i].pctCapacity);
                                _.set(peerData_scope, '[' + i + '].numEvents', success.data[i].numEvents);
                                _.set(peerData_scope, '[' + i + '].avgTktPrice', success.data[i].avgTktPrice);
                                _.set(peerData_scope, '[' + i + '].pctPaidAttendees', success.data[i].pctPaidAttendees);
                                _.set(peerData_scope, '[' + i + '].totalEvents', success.data[i].totalEvents);
                            }
                            $scope.peerData = peerData_scope;
                            $scope.showSpinner2 = false;
                            /*CLICK TO EDIT MAPPING*/
                            $scope.bulletdata = {
                                //"title": $scope.organizationData[shw].ShowTitles,
                                //"subtitle": "% Paid vs. Peers",
                                "ranges": [0, 0, 100],
                                "measures": [$scope.organizationData[shw].PctPaid],
                                "markers": [$scope.peerData[0].pctPaidAttendees],
                            };
                            $scope.capacitydata = {
                                //"title": "Show Title",
                                //"subtitle": "% of Paid Attendees vs. Peers",
                                "ranges": [0, 0, 100],
                                "measures": [$scope.organizationData[shw].PctCapacity],
                                "markers": [$scope.peerData[0].pctCapacity]
                            };
                            $scope.discretebardata = [{
                                key: "Our Price",
                                values: [{
                                        "label": "Our Price",
                                        "value": $scope.organizationData[shw].AvgTktPrice,
                                        "color": "#cc0000"
                                    },
                                    {
                                        "label": "Peer Price",
                                        "value": $scope.peerData[0].avgTktPrice,
                                        "color": "#444444"
                                    }
                                ]
                            }];
                            $scope.discretebareventdata = [{
                                key: "Our Events",
                                values: [{
                                        "label": "Our Events",
                                        "value": $scope.organizationData[shw].numEvents,
                                        "color": "#cc0000"
                                    },
                                    {
                                        "label": "Peer Events",
                                        "value": $scope.peerData[0].totalEvents,
                                        "color": "#444444"
                                    }
                                ]
                            }];
                            if ($scope.peerData[0].numEvents === 0) {
                                $scope.peerRevenue = 0;
                            } else {
                                $scope.peerRevenue = ($scope.peerData[0].netSales / $scope.peerData[0].numEvents)
                            }
                            $scope.discretebareventrevdata = [{
                                key: "Our Revenue",
                                values: [{
                                        "label": "Ours",
                                        "value": ($scope.organizationData[shw].NetSales / $scope.organizationData[shw].numEvents),
                                        "color": "#cc0000"
                                    },
                                    {
                                        "label": "Peers",
                                        "value": $scope.peerRevenue,
                                        "color": "#444444"
                                    }
                                ]
                            }];
                            if ($scope.peerData[0].numEvents === 0) {
                                var $ionicPopup = Apperyio.get("$ionicPopup");
                                var alertPopup = $ionicPopup.alert({
                                    title: 'No Peer Data Available',
                                    template: "This show does not currently have any peer data available. Check back in the future as we are constantly adding new companies and ticketing data to improve the quality and quantity of peer data for your use."
                                });
                            }
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        $scope.showSpinner2 = false;
                        var $ionicPopup = Apperyio.get("$ionicPopup");
                        var alertPopup = $ionicPopup.alert({
                            title: 'No Peer Data Available',
                            template: "This show does not currently have any peer data available. Check back in the future as we are constantly adding new companies and ticketing data to improve the quality and quantity of peer data for your use."
                        });
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function chosenShow
             * @param shw
             */
            $scope.chosenShow = function(shw) {
                $scope.show = shw;
                $scope.showSpinner2 = false;
                $scope.bulletdata = {};
                $scope.capacitydata = {};
                $scope.discretebardata = [];
                $scope.discretebareventdata = [];
                $scope.discretebareventrevdata = [];
                $scope.historicaldiscretebardata = [];
                $scope.attendanceDetails = [];
                $scope.ticketsByZip = [];
                $scope.peerData = [];
            };
            /**
             * @function home
             */
            $scope.home = function() {
                window.open("http://www.theatreprofile.com/", "_blank");
            };
            /**
             * @function shows
             */
            $scope.shows = function() {
                window.open("http://www.theatreprofile.com/show", "_blank");
            };
            /**
             * @function productions
             */
            $scope.productions = function() {
                window.open("http://www.theatreprofile.com/production", "_blank");
            };
            /**
             * @function people
             */
            $scope.people = function() {
                window.open("http://www.theatreprofile.com/people", "_blank");
            };
            /**
             * @function venues
             */
            $scope.venues = function() {
                window.open("http://www.theatreprofile.com/venue", "_blank");
            };
            /**
             * @function companies
             */
            $scope.companies = function() {
                window.open("http://www.theatreprofile.com/company", "_blank");
            };
            /**
             * @function news
             */
            $scope.news = function() {
                window.open("http://www.theatreprofile.com/news", "_blank");
            };
            /**
             * @function social
             */
            $scope.social = function() {
                window.open("http://www.theatreprofile.com/social", "_blank");
            };
            /**
             * @function about
             */
            $scope.about = function() {
                window.open("http://www.theatreprofile.com/about", "_blank");
            };
            /**
             * @function closeTab
             */
            $scope.closeTab = function() {
                window.close();
            };
            /**
             * @function register
             */
            $scope.register = function() {
                window.open("http://www.theatreprofile.com/user/registration", "_blank");
            };
            /**
             * @function introModal
             */
            $scope.introModal = function() {
                var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                    animation: 'slide-in-up', // The animation to show & hide with
                    focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                    backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                };
                if ($scope.windowWidth > 1499) {
                    Apperyio.get('Modals').loadModal("OnboardingModal").then(
                        function(modalInstance) {
                            modalInstance.open(modalOptions).then(function(modal) {
                                modal.scope.modal = modal;
                                modal.scope.windowWidth = $scope.windowWidth;
                                modal.show();
                            });
                        },
                        function(error) {
                            console.log(error);
                        });
                } else {
                    Apperyio.get('Modals').loadModal("OnboardingModalSmall").then(
                        function(modalInstance) {
                            modalInstance.open(modalOptions).then(function(modal) {
                                modal.scope.modal = modal;
                                modal.scope.windowWidth = $scope.windowWidth;
                                modal.show();
                            });
                        },
                        function(error) {
                            console.log(error);
                        });
                }
            };
            /**
             * @function chooseDateRange
             */
            $scope.chooseDateRange = function() {
                var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                    animation: 'slide-in-up', // The animation to show & hide with
                    focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                    backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                };
                Apperyio.get('Modals').loadModal("DateRange").then(
                    function(modalInstance) {
                        modalInstance.open(modalOptions).then(function(modal) {
                            modal.scope.modal = modal;
                            modal.scope.dateRange = $scope.dateRange;
                            modal.scope.startDate = new Date("2000-01-02");
                            modal.scope.endDate = new Date();
                            modal.scope.windowWidth = $scope.windowWidth;
                            modal.show();
                            modal.scope.$on('modal.hidden', function() {
                                if ($scope.dateRange.datesChosen === true) {
                                    $scope.datesChanged();
                                    //$scope.dateRange.datesChosen = false;
                                }
                            });
                        });
                    },
                    function(error) {
                        console.log(error);
                    });
            };
            /**
             * @function datesChanged
             */
            $scope.datesChanged = function() {
                $scope.piedata = [];
                $scope.organizationData = [];
                $scope.bulletdata = {};
                $scope.capacitydata = {};
                $scope.horizontalbardata = [];
                $scope.discretebardata = [];
                $scope.discretebareventdata = [];
                $scope.discretebareventrevdata = [];
                $scope.show = null;
                $scope.button = "organization";
            };
        }
    });