define(['require'], function(require) {
    /**
     * Routing configuration generated by Appery.io
     */

    /**
     * Default route
     * @type {{redirectTo: string}}
     */
    var default_route = {
        redirectTo: '/DashboardOrganization.html'
    };

/**
     * Routing configuration object
     * @property {object} default                               - Default routing configuration
     * @property {string} default.redirectTo                    - Default routing URL
     * @property {object} when                                  - Routing configuration for different URLs
     * @property {object} when./                                - Routing configuration for "/" URL
     * @property {string} when./.redirectTo                     - Redirect to default routing URL
     * @property {object} when["/DashboardOrganization.html"]    - Routing configuration for /DashboardOrganization.html URL
     * @property {string} when["/DashboardOrganization.html"].c  - Controller for /DashboardOrganization.html URL
     * @property {string} when["/DashboardOrganization.html"].t  - Template for /DashboardOrganization.html URL
     * @property {string[]} when["/DashboardOrganization.html"].d  - Dependencies for /DashboardOrganization.html URL

     * @property {object} otherwise                             - Routing configuration for another URL
     * @property {object} otherwise.redirectTo                  - Redirect to default routing URL
     * @property {object} route_names                           - Route aliases
     * @property {string} route_names.["DashboardOrganization"]  - "DashboardOrganization" is an alias for "/DashboardOrganization.html" routing

     */
    return {
    default:
        default_route, when: {
            '/': default_route,
            '/DashboardOrganization.html': {
                c: '$DashboardOrganization/DashboardOrganizationController',
                t: '$DashboardOrganization/DashboardOrganizationTemplate.html',
                d: []
            }

        },
        otherwise: default_route,
        route_names: {
            'DashboardOrganization': '/DashboardOrganization.html'

        }
    };
});