define(['require'],
    function(require) {
        /**
         * Controller for TheatreProfile generated by Appery.io
         * @module TheatreProfile
         */
        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.keys = Apperyio.EntityAPI('Keys');
            $scope.organizations = Apperyio.EntityAPI('Organizations');
            $scope.org = Apperyio.EntityAPI('Number');
            $scope.windowWidth = Apperyio.EntityAPI('Number');
            $scope.otherkeys = Apperyio.EntityAPI('OtherKeys');
            $scope.windowHeight = Apperyio.EntityAPI('Number');
            $scope.dateRange = Apperyio.EntityAPI('DateRange');
            $scope.activeKey = Apperyio.EntityAPI('String');
            $scope.sessionData = Apperyio.EntityAPI('SessionData');
            $scope.ipAddress = Apperyio.EntityAPI('String');
            $scope.privateIP = Apperyio.EntityAPI('String');
            $scope.userValid = Apperyio.EntityAPI('String');
            $scope.orgsLoading = Apperyio.EntityAPI('Boolean');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                $scope.screenSize();
                $scope.getPrivateIP();
                $scope.getActiveKey();
                $scope.visionStatus = {};
                $scope.dateRange.startDate = '2000-01-01';
                $scope.dateRange.endDate = new Date().toISOString().slice(0, 10);
                $scope.dateRange.datesChosen = false;
                $scope.orgsLoading = true;
                var requestData = {};
                requestData = (function mapping8018($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var activeKey_scope = $scope.activeKey;
                    requestData.params.activeKey = activeKey_scope;
                    return requestData;
                    /*|button_mapping|onbeforesend|319015F9-513C-BA38-976C-C8D108A6E9CF||8018|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("TPretrieveUserInformation")(requestData).then( /*|service_bookmark|bookmark|319015F9-513C-BA38-976C-C8D108A6E9CF||3362|*/
                    function(success) { // success callback
                        (function mapping8554(success, $scope) {
                            var sessionData_scope = $scope.sessionData;
                            _.set(sessionData_scope, 'id', success.data.id);
                            _.set(sessionData_scope, 'userID', success.data.userID);
                            _.set(sessionData_scope, 'activeKey', success.data.activeKey);
                            _.set(sessionData_scope, 'ipAddress', success.data.ipAddress);
                            _.set(sessionData_scope, 'expirationDate', success.data.expirationDate);
                            _.set(sessionData_scope, 'status', success.data.status);
                            _.set(sessionData_scope, 'user', success.data.user);
                            _.set(sessionData_scope, 'user.id', success.data.user.id);
                            _.set(sessionData_scope, 'user.username', success.data.user.username);
                            _.set(sessionData_scope, 'user.email', success.data.user.email);
                            $scope.sessionData = sessionData_scope;
                            /*|button_mapping|onsuccess|319015F9-513C-BA38-976C-C8D108A6E9CF||8554|*/
                            if ($scope.activeKey == $scope.sessionData.activeKey) {
                                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                                Apperyio.get("Secret_Keys_read_service")(requestData).then(
                                    function(success) { // success callback
                                        (function mapping3529(success, $scope) {
                                            var otherkeys_scope = $scope.otherkeys;
                                            _.set(otherkeys_scope, 'otheradmin', success.data.admin);
                                            _.set(otherkeys_scope, 'otherpassword', success.data.password);
                                            _.set(otherkeys_scope, 'otherhost', success.data.host);
                                            $scope.otherkeys = otherkeys_scope;
                                            /*CLICK TO EDIT MAPPING*/
                                        })(success, $scope);
                                    },
                                    function(error) { // callback to handle request error
                                    },
                                    function(notify) { // notify callback, can fire few times
                                    });
                                var requestData = {};
                                /*CLICK TO EDIT MAPPING*/
                                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                                Apperyio.get("TheatreProfile_Keys_read_service")(requestData).then(
                                    function(success) { // success callback
                                        (function mapping6126(success, $scope) {
                                            var keys_scope = $scope.keys;
                                            keys_scope = success.data;
                                            _.set(keys_scope, 'admin', success.data.admin);
                                            _.set(keys_scope, 'password', success.data.password);
                                            _.set(keys_scope, 'host', success.data.host);
                                            _.set(keys_scope, 'companytable', success.data.companytable);
                                            _.set(keys_scope, 'dbname', success.data.dbname);
                                            _.set(keys_scope, 'tickettable', success.data.tickettable);
                                            _.set(keys_scope, 'venuetable', success.data.venuetable);
                                            _.set(keys_scope, 'usertable', success.data.usertable);
                                            _.set(keys_scope, 'eventtable', success.data.eventtable);
                                            _.set(keys_scope, 'productiontable', success.data.productiontable);
                                            _.set(keys_scope, 'geotable', success.data.geotable);
                                            _.set(keys_scope, 'tatheatredb', success.data.tatheatredb);
                                            _.set(keys_scope, 'tpshowtable', success.data.tpshowtable);
                                            _.set(keys_scope, 'showtable', success.data.showtable);
                                            _.set(keys_scope, 'ownershiptable', success.data.ownershiptable);
                                            _.set(keys_scope, 'tpcompanytable', success.data.tpcompanytable);
                                            $scope.keys = keys_scope;
                                            /*CLICK TO EDIT MAPPING*/
                                            window.setTimeout(function() {
                                                $scope.$apply(function() {
                                                    var requestData = {};
                                                    requestData = (function mapping5922($scope) {
                                                        var requestData = {};
                                                        requestData.data = {};
                                                        var sessionData_scope = $scope.sessionData;
                                                        var privateIP_scope = $scope.privateIP;
                                                        var otherkeys_scope = $scope.otherkeys;
                                                        _.set(requestData.data, 'userID', sessionData_scope.userID);
                                                        _.set(requestData.data, 'activeKey', sessionData_scope.activeKey);
                                                        _.set(requestData.data, 'ipAddress', privateIP_scope);
                                                        _.set(requestData.data, 'admin', otherkeys_scope.otheradmin);
                                                        _.set(requestData.data, 'password', otherkeys_scope.otherpassword);
                                                        _.set(requestData.data, 'host', otherkeys_scope.otherhost);
                                                        return requestData;
                                                        /*|button_mapping|onbeforesend|A007B16A-43B5-AD1F-ECB1-0861B6CCBAE0||5922|*/
                                                    })($scope);
                                                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                                                    Apperyio.get("rstudioTPuserValidCheck")(requestData).then( /*|service_bookmark|bookmark|A007B16A-43B5-AD1F-ECB1-0861B6CCBAE0||6623|*/
                                                        function(success) { // success callback
                                                            (function mapping6836(success, $scope) {
                                                                var userValid_scope = $scope.userValid;
                                                                userValid_scope = success.data[0];
                                                                $scope.userValid = userValid_scope;
                                                                /*|button_mapping|onsuccess|A007B16A-43B5-AD1F-ECB1-0861B6CCBAE0||6836|*/
                                                                if ($scope.userValid == 'TRUE') {
                                                                    $scope.getUserCompanies();
                                                                } else {
                                                                    var $ionicPopup = Apperyio.get("$ionicPopup");
                                                                    var alertPopup = $ionicPopup.alert({
                                                                        title: 'Session No Longer Active',
                                                                        template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                                                                    });
                                                                }
                                                            })(success, $scope);
                                                        },
                                                        function(error) { // callback to handle request error
                                                            window.alert('An error occurred. Please refresh the page.');
                                                        },
                                                        function(notify) { // notify callback, can fire few times
                                                        });
                                                });
                                            }, 1000);
                                        })(success, $scope);
                                    },
                                    function(error) { // callback to handle request error
                                    },
                                    function(notify) { // notify callback, can fire few times
                                    });
                            } else {
                                var $ionicPopup = Apperyio.get("$ionicPopup");
                                var alertPopup = $ionicPopup.alert({
                                    title: 'Session No Longer Active',
                                    template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                                });
                            }
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        var $ionicPopup = Apperyio.get("$ionicPopup");
                        var alertPopup = $ionicPopup.alert({
                            title: 'Session No Longer Active',
                            template: "This session is no longer active. To access this dashboard, you must login to your Theatre Profile account and visit Reports."
                        });
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function screenSize
             */
            $scope.screenSize = function() {
                $scope.windowWidth = window.innerWidth;
                $scope.windowHeight = window.innerHeight;
                if ($scope.windowWidth < $scope.windowHeight) {
                    var $ionicPopup = Apperyio.get("$ionicPopup");
                    var alertPopup = $ionicPopup.alert({
                        title: 'Please Rotate To Landscape',
                        template: "In order to achieve the best viewing experience, please rotate your device to landscape mode and refresh the page."
                    });
                }
            };
            /**
             * @function sessionCheck
             */
            $scope.sessionCheck = function() {
                /*window.setTimeout(function() {      
    $scope.$apply(function() {         
        var $ionicPopup = Apperyio.get("$ionicPopup");
        var alertPopup = $ionicPopup.alert({
           title: 'Logged In',
           template: "Check complete."
        });
        $scope.sessionCheck();
    });  
}, 60000);*/
            };
            /**
             * @function getActiveKey
             */
            $scope.getActiveKey = function() {
                $scope.activeKey = window.location.search.substr(1);
            };
            /**
             * @function getPrivateIP
             */
            $scope.getPrivateIP = function() {
                var fingerprint = (function(window, screen, navigator) {
                    // https://github.com/darkskyapp/string-hash
                    function checksum(str) {
                        var hash = 5381,
                            i = str.length;
                        while (i--) hash = (hash * 33) ^ str.charCodeAt(i);
                        return hash >>> 0;
                    }
                    // http://stackoverflow.com/a/4167870/1250044
                    function map(arr, fn) {
                        var i = 0,
                            len = arr.length,
                            ret = [];
                        while (i < len) {
                            ret[i] = fn(arr[i++]);
                        }
                        return ret;
                    }
                    return checksum([
                        navigator.userAgent, [screen.height, screen.width, screen.colorDepth].join('x'),
                        new Date().getTimezoneOffset(), !!window.sessionStorage, !!window.localStorage,
                        map(navigator.plugins, function(plugin) {
                            return [
                                plugin.name,
                                plugin.description,
                                map(plugin, function(mime) {
                                    return [mime.type, mime.suffixes].join('~');
                                }).join(',')
                            ].join("::");
                        }).join(';')
                    ].join('###'));
                }(this, screen, navigator));
                $scope.privateIP = fingerprint;
            };
            /**
             * @function getUserCompanies
             */
            $scope.getUserCompanies = function() {
                $scope.showSpinner2 = true;
                var requestData = {};
                requestData = (function mapping3722($scope) {
                    var requestData = {};
                    requestData.data = {};
                    var sessionData_scope = $scope.sessionData;
                    var keys_scope = $scope.keys;
                    _.set(requestData.data, 'userID', sessionData_scope.userID);
                    _.set(requestData.data, 'admin', keys_scope.admin);
                    _.set(requestData.data, 'password', keys_scope.password);
                    _.set(requestData.data, 'host', keys_scope.host);
                    _.set(requestData.data, 'companytable', keys_scope.companytable);
                    _.set(requestData.data, 'ownershiptable', keys_scope.ownershiptable);
                    _.set(requestData.data, 'tpcompanytable', keys_scope.tpcompanytable);
                    _.set(requestData.data, 'dbname', keys_scope.dbname);
                    return requestData;
                    /*CLICK TO EDIT MAPPING*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("rstudioTPcompaniesLinkedUserID")(requestData).then(
                    function(success) { // success callback
                        (function mapping4879(success, $scope) {
                            var organizations_scope = $scope.organizations;
                            for (var i = 0, l = success.data.length; i < l; i++) {
                                _.set(organizations_scope, '[' + i + '].id', success.data[i].id);
                                _.set(organizations_scope, '[' + i + '].index', success.data[i].index);
                                _.set(organizations_scope, '[' + i + '].orgNames', success.data[i].companyName);
                            }
                            $scope.organizations = organizations_scope;
                            /*CLICK TO EDIT MAPPING*/
                            $scope.orgsLoading = false;
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
        }
        return ['$scope', 'Apperyio', controller];
    });