define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for DateRange generated by Appery.io
         * @module DateRange
         */
        APP.controller('DateRangeController', ['$scope', 'Apperyio', DateRangeController]);

        function DateRangeController($scope, Apperyio) {
            // user controller variables
            // user controller functions
            /**
             * @function closeModal
             */
            $scope.closeModal = function() {
                $scope.modal.hide();
            };
            /**
             * @function selectDates
             * @param start
             * @param end
             */
            $scope.selectDates = function(start, end) {
                $scope.$parent.$parent.dateRange.startDate = start.toISOString().slice(0, 10);
                $scope.$parent.$parent.dateRange.endDate = end.toISOString().slice(0, 10);
                $scope.$parent.$parent.dateRange.datesChosen = true;
                var send = $scope.$parent.$parent.dateRange;
                $scope.modal.hide(send);
            };
            /**
             * @function resetDates
             */
            $scope.resetDates = function() {
                $scope.$parent.$parent.dateRange.startDate = '2000-01-01';
                $scope.$parent.$parent.dateRange.endDate = new Date().toISOString().slice(0, 10);
                $scope.$parent.$parent.dateRange.datesChosen = true;
                var send = $scope.$parent.$parent.dateRange;
                $scope.modal.hide(send);
            };
        }
    });